#!/bin/bash

envs=("prod" "dev" "stage")

get_environment_int(){
  local default_env
  if [ -n $1 ]
  then
    default_env=$1
  else
    default_env=$(echo $ENV)
  fi

  if [ -z "$default_env" ]
  then
    default_env=${envs[0]}
  fi

  local environment=""
  while true
  do
    read -p "Specify environment [$default_env]: " environment
    # default prod
    if [ -z "$environment" ]
    then
      environment="$default_env"
    fi
    # lowercase
    environment=$(echo $environment | tr '[:upper:]' '[:lower:]')
    # in array of possible envs

    for i in "${!envs[@]}"; do
       if [[ "${envs[$i]}" = "$environment" ]]; then
           return $i
       fi
    done
    echo "Invalid environment \"$environment\" specified! Should be one of [${envs[@]}]."
  done
}

function get_env() {
  if [ -n $1 ]
  then
    get_environment_int $1
  else
    get_environment_int
  fi

  echo ${envs[$?]}
}